# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 489)
        MainWindow.setMinimumSize(QtCore.QSize(120, 120))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.tab)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setStyleSheet("background-color: #F0F8FF;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_2.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.widget_4)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.read_button = QtWidgets.QPushButton(self.widget_2)
        self.read_button.setMinimumSize(QtCore.QSize(180, 30))
        self.read_button.setMaximumSize(QtCore.QSize(180, 30))
        self.read_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.read_button.setStyleSheet("\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color: #FFD700;\n"
"    \n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(255, 161, 75);\n"
"    border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    font: 9pt \"微软雅黑\"  ;\n"
"}\n"
"")
        self.read_button.setObjectName("read_button")
        self.verticalLayout_10.addWidget(self.read_button)
        self.curtailnum_layout = QtWidgets.QHBoxLayout()
        self.curtailnum_layout.setObjectName("curtailnum_layout")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setStyleSheet("QLabel{\n"
"    \n"
"    font: 8pt \"微软雅黑\";\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")
        self.curtailnum_layout.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.curtailnum_layout.addWidget(self.lineEdit_2)
        self.curtailnum_layout.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.curtailnum_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.text_layout1 = QtWidgets.QHBoxLayout()
        self.text_layout1.setObjectName("text_layout1")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setStyleSheet("font: 8pt \"微软雅黑\";")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.text_layout1.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("QLabel{\n"
"    border:0px solid lightgray; \n"
"    image: url(:/icon/resources/停止.png);\n"
"}\n"
"")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.text_layout1.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setEnabled(True)
        self.label_7.setStyleSheet("QLabel{\n"
"    border:0px solid lightgray; \n"
"    image: url(:/icon/resources/执行.png);\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.text_layout1.addWidget(self.label_7)
        self.text_layout1.setStretch(1, 1)
        self.text_layout1.setStretch(2, 1)
        self.verticalLayout_10.addLayout(self.text_layout1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addWidget(self.widget_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_7 = QtWidgets.QWidget(self.tab_2)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_5 = QtWidgets.QWidget(self.widget_7)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.text_widget = QtWidgets.QWidget(self.widget_5)
        self.text_widget.setStyleSheet("QWidget#text_widget{\n"
"    border:0.5px solid lightgray; \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.text_widget.setObjectName("text_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.text_widget)
        self.verticalLayout_5.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.text_widget)
        self.label_3.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"background-color: #F0F8FF;\n"
"border-top:2px;\n"
"border-bottom:1px solid lightgray;\n"
"padding-bottom:8px ;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.text_widget)
        self.tableWidget_2.setStyleSheet("border:0px;\n"
"background-color: #F0F8FF;")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_2)
        self.verticalLayout_4.addWidget(self.text_widget)
        self.verticalLayout_6.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_7)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_6)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: transparent;\n"
"font: 9pt \"微软雅黑\";\n"
"border: 0px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_8 = QtWidgets.QLabel(self.widget_6)
        self.label_8.setMinimumSize(QtCore.QSize(0, 100))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_8.setStyleSheet("QWidget#label_8{\n"
"background-color: #00FA9A;\n"
"font: 9pt \"微软雅黑\";\n"
"border: 0px;\n"
"}\n"
"")
        self.label_8.setWordWrap(True)
        self.label_8.setIndent(1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.upload_pic_5 = QtWidgets.QPushButton(self.widget_6)
        self.upload_pic_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_pic_5.sizePolicy().hasHeightForWidth())
        self.upload_pic_5.setSizePolicy(sizePolicy)
        self.upload_pic_5.setMinimumSize(QtCore.QSize(120, 45))
        self.upload_pic_5.setMaximumSize(QtCore.QSize(250, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.upload_pic_5.setFont(font)
        self.upload_pic_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.upload_pic_5.setStyleSheet("QPushButton:enabled\n"
"{\n"
"    background-color: #1E90FF;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    font: 11.5pt \"微软雅黑\"  ;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color: rgb(253, 149, 54);\n"
"    \n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color: lightgray;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    font: 11.5pt \"微软雅黑\"  ;\n"
"    \n"
"}")
        self.upload_pic_5.setFlat(False)
        self.upload_pic_5.setObjectName("upload_pic_5")
        self.horizontalLayout_3.addWidget(self.upload_pic_5)
        self.upload_pic_6 = QtWidgets.QPushButton(self.widget_6)
        self.upload_pic_6.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_pic_6.sizePolicy().hasHeightForWidth())
        self.upload_pic_6.setSizePolicy(sizePolicy)
        self.upload_pic_6.setMinimumSize(QtCore.QSize(120, 45))
        self.upload_pic_6.setMaximumSize(QtCore.QSize(250, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.upload_pic_6.setFont(font)
        self.upload_pic_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.upload_pic_6.setStyleSheet("QPushButton:enabled\n"
"{\n"
"    background-color: #1E90FF;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    font: 11.5pt \"微软雅黑\"  ;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color: rgb(253, 149, 54);\n"
"    \n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color: lightgray;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    font: 11.5pt \"微软雅黑\"  ;\n"
"    \n"
"}")
        self.upload_pic_6.setFlat(False)
        self.upload_pic_6.setObjectName("upload_pic_6")
        self.horizontalLayout_3.addWidget(self.upload_pic_6)
        self.verticalLayout_6.addWidget(self.widget_6)
        self.verticalLayout_7.addWidget(self.widget_7)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_10 = QtWidgets.QWidget(self.tab_3)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_9 = QtWidgets.QWidget(self.widget_10)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.widget_9)
        self.label_12.setStyleSheet("font: 20pt \"微软雅黑\";\n"
"background-color: #F0F8FF;\n"
"border-top:2px;\n"
"border-bottom:1px solid lightgray;\n"
"padding-bottom:8px ;")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.verticalLayout_8.addWidget(self.widget_9)
        self.widget_8 = QtWidgets.QWidget(self.widget_10)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.text_widget_2 = QtWidgets.QWidget(self.widget_8)
        self.text_widget_2.setStyleSheet("QWidget#text_widget{\n"
"    border:0.5px solid lightgray; \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.text_widget_2.setObjectName("text_widget_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.text_widget_2)
        self.verticalLayout_11.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.text_widget_2)
        self.label_9.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"background-color: #F0F8FF;\n"
"border-top:2px;\n"
"border-bottom:1px solid lightgray;\n"
"padding-bottom:8px ;")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_11.addWidget(self.label_9)
        self.label_2 = QtWidgets.QLabel(self.text_widget_2)
        self.label_2.setStyleSheet("background-color: #F0F8FF;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.verticalLayout_11.setStretch(0, 1)
        self.verticalLayout_11.setStretch(1, 15)
        self.horizontalLayout_4.addWidget(self.text_widget_2)
        self.text_widget_3 = QtWidgets.QWidget(self.widget_8)
        self.text_widget_3.setStyleSheet("QWidget#text_widget{\n"
"    border:0.5px solid lightgray; \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.text_widget_3.setObjectName("text_widget_3")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.text_widget_3)
        self.verticalLayout_12.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.text_widget_3)
        self.label_10.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"background-color: #F0F8FF;\n"
"border-top:2px;\n"
"border-bottom:1px solid lightgray;\n"
"padding-bottom:8px ;")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_12.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.text_widget_3)
        self.label_11.setStyleSheet("background-color: #F0F8FF;")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.verticalLayout_12.setStretch(0, 1)
        self.verticalLayout_12.setStretch(1, 15)
        self.horizontalLayout_4.addWidget(self.text_widget_3)
        self.verticalLayout_8.addWidget(self.widget_8)
        self.verticalLayout_13.addWidget(self.widget_10)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.read_button.setText(_translate("MainWindow", "截取数据包"))
        self.label_4.setText(_translate("MainWindow", "截取数量"))
        self.lineEdit_2.setText(_translate("MainWindow", "4000"))
        self.label_6.setText(_translate("MainWindow", "程序未运行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "流量提取"))
        self.label_3.setText(_translate("MainWindow", "识别结果"))
        self.label.setText(_translate("MainWindow", "页面说明："))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">本页面用于展示截取流量的标签：</span></p><p align=\"center\"><span style=\" font-size:8pt;\">页面分别展示源ip地址，目的ip地址，源端口，目的端口，协议及数据类型。（对于协议而言: </span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:8pt; color:#000000;\">6:TCP 17:UDP 1:ICMP)</span></p><p align=\"center\"><br/></p><p><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:8pt; color:#000000;\">（2）我们主要使用2个训练集，分别是ISCX 2012 和CIC-IDS 2017。</span></p><p><span style=\" font-size:8pt;\"><br/></span></p></body></html>"))
        self.upload_pic_5.setText(_translate("MainWindow", "开始识别"))
        self.upload_pic_6.setText(_translate("MainWindow", "可视化分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "流量鉴别"))
        self.label_12.setText(_translate("MainWindow", "流量可视化分析"))
        self.label_9.setText(_translate("MainWindow", "柱状图"))
        self.label_10.setText(_translate("MainWindow", "饼形图"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "可视化"))
        self.action_2.setText(_translate("MainWindow", "流量提取"))
        self.action_3.setText(_translate("MainWindow", "流量鉴别"))
